' the same task name appear multiple times

!procedure N(x,n)
[x<size:0>n</size>]
!endprocedure

' accuracy level

!function $accuracy_color($accuracy)
    !$r=HIGH_ACC_COL
    !if $accuracy == "Low"
        !$r=LOW_ACC_COL
    !endif
    !if $accuracy == "Middle"
        !$r=MIDDLE_ACC_COL
    !endif
    !return $r
!end function